const forms = {
  input: {
    p: 1,
    fontFamily: "paragraph",
    fontSize: "p1",
    fontWeight: "regular",
    lineHeight: "paragraph",
    letterSpacings: "paragraph",
    fontStyle: "paragraph",
    color: "text-primary",
    borderColor: "gray-200",
  },
  select: {
    p: 1,
    fontFamily: "paragraph",
    fontSize: "p1",
    fontWeight: "regular",
    lineHeight: "paragraph",
    letterSpacings: "paragraph",
    fontStyle: "paragraph",
    color: "text-primary",
    borderColor: "gray-200",
  },
  textarea: {
    p: 1,
    fontFamily: "paragraph",
    fontSize: "p1",
    fontWeight: "regular",
    lineHeight: "paragraph",
    letterSpacings: "paragraph",
    fontStyle: "paragraph",
    color: "text-primary",
    borderColor: "gray-200",
  },
  label: {
    fontFamily: "paragraph",
    fontSize: "p1",
    fontWeight: "regular",
    lineHeight: "paragraph",
    letterSpacings: "paragraph",
    fontStyle: "paragraph",
    color: "text-tertiary",
  },
  radio: {
    p: 1,
    fontFamily: "paragraph",
    fontSize: "p1",
    fontWeight: "regular",
    lineHeight: "paragraph",
    letterSpacings: "paragraph",
    fontStyle: "paragraph",
    color: "text-primary",
  },
  checkbox: {
    p: 1,
    fontFamily: "label",
    fontSize: "l1",
    fontWeight: "regular",
    lineHeight: "label",
    letterSpacings: "label",
    fontStyle: "label",
    color: "text-primary",
  },
}

export default forms;