const text = {
  h1: {
    fontFamily: "headline",
    fontSize: "h1",
    fontWeight: "medium",
    lineHeight: "headline",
    letterSpacings: "headline",
    fontStyle: "headline",
    color: "text-primary",
  },
  h2: {
    fontFamily: "headline",
    fontSize: "h2",
    fontWeight: "medium",
    lineHeight: "headline",
    letterSpacings: "headline",
    fontStyle: "headline",
    color: "text-primary",
  },
  h3: {
    fontFamily: "headline",
    fontSize: "h3",
    fontWeight: "medium",
    lineHeight: "headline",
    letterSpacings: "headline",
    fontStyle: "headline",
    color: "text-primary",
  },
  h4: {
    fontFamily: "headline",
    fontSize: "h4",
    fontWeight: "medium",
    lineHeight: "headline",
    letterSpacings: "headline",
    fontStyle: "headline",
    color: "text-primary",
  },
  h5: {
    fontFamily: "headline",
    fontSize: "h5",
    fontWeight: "medium",
    lineHeight: "headline",
    letterSpacings: "headline",
    fontStyle: "headline",
    color: "text-primary",
  },
  s1: {
    fontFamily: "subtitle",
    fontSize: "s1",
    fontWeight: "medium",
    lineHeight: "subtitle",
    letterSpacings: "subtitle",
    fontStyle: "subtitle",
    color: "text-primary",
  },
  s2: {
    fontFamily: "subtitle",
    fontSize: "s2",
    fontWeight: "medium",
    lineHeight: "subtitle",
    letterSpacings: "subtitle",
    fontStyle: "subtitle",
    color: "text-primary",
  },
  p1: {
    fontFamily: "paragraph",
    fontSize: "p1",
    fontWeight: "regular",
    lineHeight: "paragraph",
    letterSpacings: "paragraph",
    fontStyle: "paragraph",
    color: "text-primary",
  },
  p2: {
    fontFamily: "paragraph",
    fontSize: "p2",
    fontWeight: "regular",
    lineHeight: "paragraph",
    letterSpacings: "paragraph",
    fontStyle: "paragraph",
    color: "text-primary",
  },
  l1: {
    fontFamily: "label",
    fontSize: "l1",
    fontWeight: "regular",
    lineHeight: "label",
    letterSpacings: "label",
    fontStyle: "label",
    color: "text-tertiary",
  },
}

export default text;